from flask import Flask,request,jsonify
import subprocess
import pyrebase
import os
import whisper
from IPython.display import Audio
from IPython.display import HTML
from base64 import b64encode
# from whisper.utils import WriteVTT
import json
import os
import zlib
from typing import Callable, TextIO
config ={
  "apiKey": "AIzaSyBYQeZdLdxOBFVb2KgvbFP6bxT5m5GbQEg",
  "authDomain": "back-ea132.firebaseapp.com",
  "projectId": "back-ea132",
  "storageBucket": "back-ea132.appspot.com",
  "serviceAccount": "serviceAccountKey.json",
  "messagingSenderId": "1074209921814",
  "appId": "1:1074209921814:web:f0dd29d585d3a195890e37",
  "databaseURL":" "
}
firebase_storage = pyrebase.initialize_app(config)
storage = firebase_storage.storage()
app = Flask(__name__)
@app.route("/", methods=['GET'])
def home():
    filename=str(request.args['query'])
    storage.download("files/{}".format(filename),"video.mp4")
    subprocess.run(["python","model.py"])
    print("video subtitled sucess")
    file_path = "video_Subtitled.mp4"
    remote_path = "files_sub/{}".format(filename)
    storage.child(remote_path).put(file_path)
    subprocess.run(["python","shift.py"])#copying the subtitled video
    subprocess.run(["python","remove.py"])#removing the files generated by model
    dic={}
    dic['output'] = filename
    return jsonify(dic)  
if __name__ == "__main__":
    app.run()